### ISSUE TITLE
Embedded CSS conflicts with default styling

### ISSUE THREAD

**Issue by luckman212** [logancyang/obsidian-copilot#10]
> Tested w. Copilot v1.2.1

The following CSS overrides default `p` and `ul` styles causing a problem with their margins:

https://github.com/logancyang/obsidian-copilot/blob/5ababd8e122c5f5748fb1554294e289952f88fa2/styles.css#L163-L172

### Example

<img width="540" alt="screenshot_fgEEFKa6_gh" src="https://github.com/logancyang/obsidian-copilot/assets/1992842/ad19859a-263f-4291-9936-c701a17a98c1">

### I edited the CSS to this, seems to fix it

```css
.message-content pre, .message-content p {
  margin: 0;
  padding: 0;
}

.message-content ol, .message-content ul {
  list-style: none;
  padding-left: 20px;
  margin: 0;
}
```
