### ISSUE TITLE
User system prompt field shrinks when adjusted.

### ISSUE THREAD

**Issue by ksdavidc** [logancyang/obsidian-copilot#1071]
Using a fresh vault I get this behavior:

https://github.com/user-attachments/assets/ced56e2b-5413-4e54-af6a-cbb346d518ea

It remains shrunk on open. 

The following css sort of fixes it, but probably not properly.

.w-full {
min-width: max-content;
}

**Comment by ksdavidc** [comment]
I found that 

```css
.w-full {
min-width: max-content;
}
```

messes with the results. I think 

```css
.w-full {
min-width: fit-content;
}
```

works better
