### ISSUE TITLE
Can't add OpenAI Key (but others work)

### ISSUE THREAD

**Issue by SedrickHeiniger** [logancyang/obsidian-copilot#1557]
- [X] Disable all other plugins besides Copilot **(required)**
- [X] Screenshot of note + Copilot chat pane + dev console added **(required)**

Copilot version: 2.9.0

**Describe how to reproduce**

I get an error message when adding OpenAI Key (see screenshots). 

- Create new OpenAI key
  - Owned By: You
  - Project: Default Project
  - Permissions: All

- Open "Basic" Tab in Copilot Settings
- Open "Set Keys"
- Put OpenAI Key into OpenAI Field
- (maybe change model. It happens no matter if I change to GPT-o4-mini or not)
- Press "Verify"

**What I Expected**

To setup OpenAI and being able to use it afterwards. I can't. Instead I get error meesages. The OpenAI Key is reset in "Set Key" after closing the window. 

**Screenshots**

![Image](https://github.com/user-attachments/assets/d1ca3bd9-d0f3-498c-a15c-fda7075aea41)

**Additional Context**

- I was able to add Gemini Key and it works (I haven't tested any others). 

These messages pop up after closing the "Set Keys" window after closing it. The keys are reset after that. 

![Image](https://github.com/user-attachments/assets/bfc28378-2a71-4f99-b8e4-64fc7674adfe)

Debug Info: 

``` yaml
SYSTEM INFO:
	Obsidian version: v1.8.10
	Installer version: v1.8.9
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Copilot v2.9.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
